# | =================================================== |
# | Thank you for downloading and trying out my plugin: |
# |                       Quests                        |
# |      https://www.spigotmc.org/resources/23696/      |
# |         https://github.com/LMBishop/Quests/         |
# |                                                     |
# |                         =x=                         |
# |                                                     |
# |              File comments should help              |
# |               you with the new config               |
# |              and guide you with making              |
# |                        quests                       |
# |                                                     |
# |                         =x=                         |
# |                                                     |
# |              Have Discord & need help?              |
# |           https://www.discord.gg/8amrJnX            |
# | =================================================== |

# Categories are a way of grouping up quests.
# When a player uses /quests, a menu of categories will be presented to them.
# When a player clicks ona category, a list of quests under that category will show.
# If categories are disabled, all quests will be shown under one big GUI.
# Players can access specific categories by command using /quests c [category].
# If a quest does not have a category, it will not be shown.
categories:
  farming:
    display:
      name: "&r"
      lore:
        - "&r      &a&l&m---&r&8&l&m[--&r     &8* &a&nFarming Quests&r &8*&r     &8&l&m--]&a&l&m---"
        - "&r"
        - "&7Quests that require you to gather some resources"
        - "&7        that may involve farming are found here."
        - "&r"
        - "&7➤ Quests in this category: &a&n78"
        - "&r"
        - "&7Quest Difficulty: &aEasy&7-&cHard"
        - "&7* Complete a quest to get a reward!"
        - "&r"
        - "&a&l&m---&r&8&l&m[--&r              &8&m*----------*&r              &8&l&m--]&a&l&m---"
      type: "296"
  mining:
    display:
      name: "&r"
      lore:
        - "&r   &b&l&m---&r&8&l&m[--&r     &8* &b&nMining Quests&r &8*&r     &8&l&m--]&b&l&m---"
        - "&r"
        - "&7Quests that require you to mine certain"
        - "&7  blocks can be found in this category."
        - "&r"
        - "&7➤ Quests in this category: &b&n31"
        - "&r"
        - "&7Quest Difficulty: &aEasy&7-&cHard"
        - "&7* Complete a quest to get a reward!"
        - "&r"
        - "&b&l&m---&r&8&l&m[--&r           &8&m*----------*&r           &8&l&m--]&b&l&m---"
      type: "278"
  nightmare:
    display:
      name: "&r"
      lore:
        - "&r  &4&l&m---&r&8&l&m[--&r     &8* &4&nNightmare Quests&r &8*&r     &8&l&m--]&4&l&m---"
        - "&r"
        - "&7Quests and riddles can be found here which"
        - "&7   can be very hard to solve and complete!"
        - "&r"
        - "&7➤ Solve the riddle and have the necessary"
        - "&7item in your inventory to complete the quest!"
        - "&r"
        - "&7➤ Quests in this category: &4&n22"
        - "&r"
        - "&7Quest Difficulty: &4Nightmare"
        - "&7* Complete a quest to get an &nAMAZING&r&7 reward!"
        - "&r"
        - "&4&l&m---&r&8&l&m[--&r            &8&m*----------*&r            &8&l&m--]&4&l&m---"
      type: "397:1"
  gathering:
    display:
      name: "&r"
      lore:
        - "&r &f&l&m---&r&8&l&m[--&r     &8* &f&nGathering Quests&r &8*&r     &8&l&m--]&f&l&m---"
        - "&r"
        - "&7Quests that require you to gather some kind"
        - "&7 of resources can be found in the category!"
        - "&r"
        - "&7➤ Quests in this category: &f&n29"
        - "&r"
        - "&7Quest Difficulty: &aEasy&7-&eDifficult"
        - "&7* Complete a quest to get a reward!"
        - "&r"
        - "&f&l&m---&r&8&l&m[--&r            &8&m*----------*&r            &8&l&m--]&f&l&m---"
        - "&r"
      type: "325"
  extreme:
    display:
      name: "&r"
      lore:
        - "&r   &e&l&m---&r&8&l&m[--&r     &8* &e&nExtreme Quests&r &8*&r     &8&l&m--]&e&l&m---"
        - "&r"
        - "&7Quests that require you to gather ALOT of"
        - "&7 resources can be found in the category!"
        - "&r"
        - "&7➤ Quests in this category: &e&n55"
        - "&r"
        - "&7Quest Difficulty: &eDifficult&7-&cHard"
        - "&7* Complete a quest to get a reward!"
        - "&r"
        - "&e&l&m---&r&8&l&m[--&r            &8&m*----------*&r            &8&l&m--]&e&l&m---"
        - "&r"
      type: "338"
  combat:
    display:
      name: "&r"
      lore:
        - "&r   &c&l&m---&r&8&l&m[--&r     &8* &c&nCombat Quests&r &8*&r     &8&l&m--]&c&l&m---"
        - "&r"
        - "&7Quests that require you to attack other"
        - "&7players and monsters can be found here."
        - "&r"
        - "&7➤ Quests in this category: &c&n48"
        - "&r"
        - "&7Quest Difficulty: &aEasy&7-&cHard"
        - "&7* Complete a quest to get a reward!"
        - "&r"
        - "&c&l&m---&r&8&l&m[--&r           &8&m*----------*&r           &8&l&m--]&c&l&m---"
      type: "261"
  misc:
    display:
      name: "&r"
      lore:
        - "&d&l&m---&r&8&l&m[--&r     &8* &d&nMiscellaneous Quests&r &8*&r     &8&l&m--]&d&l&m---"
        - "&r"
        - "&7Quests that do not fit into other"
        - "&7  categories can be found here."
        - "&r"
        - "&7➤ Quests in this category: &d&n11"
        - "&r"
        - "&7Quest Difficulty: &aEasy&7-&cHard"
        - "&7* Complete a quest to get a reward!"
        - "&r"
        - "&d&l&m---&r&8&l&m[--&r              &8&m*----------*&r              &8&l&m--]&d&l&m---"
        - "&r"
      type: "341"
  building:
    display:
      name: "&r"
      lore:
        - "&9&l&m---&r&8&l&m[--&r     &8* &9&nBuilding Quests&r &8*&r     &8&l&m--]&9&l&m---"
        - "&r"
        - "&7Quests that require to build something"
        - "&7     can be found in this category."
        - "&r"
        - "&7➤ Quests in this category: &9&n6"
        - "&r"
        - "&7Quest Difficulty: &aEasy&7-&cHard"
        - "&7* Complete a quest to get a reward!"
        - "&r"
        - "&9&l&m ---&r&8&l&m[--&r       &8&m*----------*&r       &8&l&m--]&9&l&m---"
        - "&r"
      type: "5"
  animal:
    display:
      name: "&r"
      lore:
        - "&3&l&m---&r&8&l&m[--&r     &b* &3&nAnimal Quests&r &b*&r     &8&l&m--]&3&l&m---"
        - "&r"
        - "&7Quests that require to you to work with animals"
        - "&7        can be found in this category."
        - "&r"
        - "&7➤ Quests in this category: &3&n12"
        - "&r"
        - "&7Quest Difficulty: &aEasy&7-&cHard"
        - "&7* Complete a quest to get a reward!"
        - "&r"
        - "&3&l&m ---&r&8&l&m[--&r       &8&m*----------*&r       &8&l&m--]&3&l&m---"
        - "&r"
      type: "334"

# The items listed below are placeholder items for quests which the player cannot start.
gui:
  back-button:
    name: "&cReturn"
    lore:
    - "&7Return to the categories menu."
    type: "ARROW"
  page-prev:
    name: "&7Previous Page"
    lore:
    - "&7Switch the page to page &c{prevpage}."
    type: "FEATHER"
  page-next:
    name: "&7Next Page"
    lore:
    - "&7Switch the page to page &c{nextpage}."
    type: "FEATHER"
  page-desc:
    name: "&7Page &c{page}"
    lore:
    - "&7You are currently viewing page &c{page}."
    type: "PAPER"
  quest-locked-display:
    name: "&c&lQuest Locked"
    lore:
    - "&7You have not completed the requirements"
    - "&7for this quest (&c{quest}&7)."
    - ""
    - "&7Requires: &c{requirements}"
    - "&7to be completed to unlock."
    type: "RED_STAINED_GLASS_PANE"
  quest-permission-display:
    name: "&6&lNo Permission"
    lore:
    - "&7You do not have permission for this"
    - "&7quest (&6{quest}&7)."
    type: "BROWN_STAINED_GLASS_PANE"
  quest-cooldown-display:
    name: "&e&lQuest On Cooldown"
    lore:
    - "&7You have recently completed this quest"
    - "&7(&e{quest}&7) and you must"
    - "&7wait another &e{time} &7to unlock again."
    type: "ORANGE_STAINED_GLASS_PANE"
  quest-completed-display:
    name: "&a&lQuest Complete"
    lore:
    - "&7You have completed this quest"
    - "&7(&a{quest}&7) and cannot."
    - "&7repeat it."
    type: "GREEN_STAINED_GLASS_PANE"
  quest-cancel-yes:
    name: "&a&lConfirm Cancel"
    lore:
    - "&7Confirm you wish to cancel"
    - "&7this quest and lose all"
    - "&7progress."
    type: "GREEN_STAINED_GLASS_PANE"
  quest-cancel-no:
    name: "&c&lAbort Cancel"
    lore:
    - "&7Return to the quest menu."
    type: "RED_STAINED_GLASS_PANE"

options:
  # If categories are disabled, quests will be put into one big gui.
  categories-enabled: true
  # If true, the gui size will automatically change based on the amount of quests inside it.
  trim-gui-size: true
  # Enable/disable titles
  titles-enabled: true
  # Players cannot start any more quests than this at a single time
  quest-started-limit: 2
  # Hide locked quests, quests on cooldown and completed (but not repeatable) quests
  gui-hide-locked: false
  # Allow players to cancel a quest
  allow-quest-cancel: true
  # Titles for the GUIs
  guinames:
    quests-category: "Quests Categories"
    quests-menu: "Quests"
    daily-quests: "Daily Quests"
    quest-cancel: "Cancel Quest"
  # Show when quests register in console. Disable if you want less console spam at startup.
  show-quest-registrations: true
  # Hide quests which a player cannot start due to permissions.
  gui-hide-quests-nopermission: true
  # Hide categories which a player cannot open due to permissions.
  gui-hide-categories-nopermission: true
  # Make it so players do not have to start quest themselves
  quest-autostart: false

# This switches up the entire quest system.
# By enabling daily-quests, players will no longer be presented with the standard Quest GUI.
# Instead, they will be presented with 5 random quests.
# The 'requirements' section in each quest does not apply here.
# The 'cooldown' section in each quest does not apply here - if it's done, it's done (and will be repeatable next time they get the quest).
# The 'repeatable' section in each quest does not apply here. It will NOT be repeatable until the next day.
# Enabling this MAY cause previous quest progress to be modified, wiped or changed irreversibly! If you're testing this on a live server, it is wise to backup
# the Quests/playerdata/ folder! You've been warned!
#
# Quests BETA: this feature is a work in progress, it does not work yet!
daily-quests:
  enabled: true

# Configure titles
titles:
  quest-start:
    title: "&cQuest Started"
    subtitle: "&7{quest}"
  quest-complete:
    title: "&cQuest Complete"
    subtitle: "&7{quest}"

# Configure messages
messages:
  quest-start: "&c&lQuests &8» &7Quest &c{quest} &7started!"
  quest-complete: "&c&lQuests &8» &7Quest &c{quest} &7completed!"
  quest-cancel: "&c&lQuests &8» &7Quest &c{quest} &7cancelled!"
  quest-start-limit: "&c&lQuests &8» &7Players are limited to &c{limit} &7started quests at a time."
  quest-start-disabled: "&c&lQuests &8» &7You cannot repeat this quest."
  quest-start-locked: "&c&lQuests &8» &7You have not unlocked this quest yet."
  quest-start-cooldown: "&c&lQuests &8» &7You have recently completed this quest. You have to wait &c{time} &7until you are able to restart it."
  quest-start-started: "&c&lQuests &8» &7You have already started this quest."
  quest-start-permission: "&c&lQuests &8» &7You do not have permission to start this quest."
  quest-category-permission: "&c&lQuests &8» &7You do not have permission to view this category."
  quest-category-quest-permission: "&c&lQuests &8» &7You do not have permission to start this quest since it is in a category you do not have permission to view."
  quest-cancel-notstarted: "&c&lQuests &8» &7You have not started this quest."
  quest-updater: "&c&lQuests &8» &7A new version &c{newver} &7was found on Spigot (your version: &c{oldver}&7). Please update me! <3 - Link: {link}"
  command-quest-start-doesntexist: "&c&lQuests &8» &7The specified quest '&c{quest}&7' does not exist."
  command-category-open-disabled: "&c&lQuests &8» &7Categories are disabled."
  command-category-open-doesntexist: "&c&lQuests &8» &7The specified category '&c{category}&7' does not exist."
  command-quest-admin-playernotfound: "&c&lQuests &8» &7Player '&c{player}&7' could not be found."
  command-quest-openquests-admin-success: "&c&lQuests &8» &7Opened Quest GUI for player &c{player}&7."
  command-quest-opencategory-admin-success: "&c&lQuests &8» &7Opened category &c{category} &7for player &c{player}&7."
  command-taskview-admin-fail: "&c&lQuests &8» &7Task type '&c{task}&7' does not exist."
  beta-reminder: "&c&lQuests &8» &7Reminder: you are currently using a &cbeta &7version of Quests. Please send bug reports to https://github.com/fatpigsarefat/Quests/issues and check for updates regularly using &c/quests admin update&7!"
  command-quest-admin-loaddata: "&c&lQuests &8» &7Quest data for '&c{player}&7' is being loaded."
  command-quest-admin-nodata: "&c&lQuests &8» &7No data could be found for player &c{player}&7."
  command-quest-admin-fullreset: "&c&lQuests &8» &7Data for player &c{player}&7 has been fully reset."
  command-quest-admin-start-faillocked: "&c&lQuests &8» &7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have not yet unlocked it."
  command-quest-admin-start-failcooldown: "&c&lQuests &8» &7Quest '&c{quest}&7' could not be started for player &c{player}&7. It is still on cooldown for them."
  command-quest-admin-start-failcomplete: "&c&lQuests &8» &7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have already completed it."
  command-quest-admin-start-faillimit: "&c&lQuests &8» &7Quest '&c{quest}&7' could not be started for player &c{player}&7. They have reached their quest start limit."
  command-quest-admin-start-failstarted: "&c&lQuests &8» &7Quest '&c{quest}&7' could not be started for player &c{player}&7. It is already started."
  command-quest-admin-start-failpermission: "&c&lQuests &8» &7Quest '&c{quest}&7' could not be started for player &c{player}&7. They do not have permission."
  command-quest-admin-start-failcategorypermission: "&c&lQuests &8» &7Quest '&c{quest}&7' could not be started for player &c{player}&7. They do not have permission for the category which the quest is in."
  command-quest-admin-start-failother: "&c&lQuests &8» &7Quest '&c{quest}&7' could not be started for player &c{player}&7."
  command-quest-admin-start-success: "&c&lQuests &8» &7Quest &c{quest} &7started for player &c{player}&7."
  command-quest-admin-category-permission: "&c&lQuests &8» &7Category &c{category} &7 could not be opened for player &c{player}&7. They do not have permission to view it."
  command-quest-admin-complete-success: "&c&lQuests &8» &7Quest &c{quest} &7completed for player &c{player}&7."
  command-quest-admin-reset-success: "&c&lQuests &8» &7Successfully reset quest '&c{quest}&7' for player &c{player}&7."